options:
  gw-id:
    type: string
    description: |
      The gateway ID of the UPF.
    default: "1"
    required: true
  mcc:
    type: string
    description: |
      The Mobile Country Code (MCC) of the UPF.
    default: "208"
    required: true
  mnc:
    type: string
    description: |
      The Mobile Network Code (MNC) of the UPF.
    default: "99"
    required: true
  realm:
    type: string
    description: |
      The realm of the UPF.
    default: "3gpp.org"
    required: true
  network-ue-ip:
    type: string
    description: |
      The UE IP address of the UPF.
    default: "12.1.1.0/24"
